version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: django_container
    command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: react_container
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"

  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
