# Generated by Django 5.0.6 on 2024-07-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_review_user_remove_video_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table='modules',
        ),
    ]
