# Generated by Django 5.0.6 on 2024-07-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_review_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
