# Generated by Django 5.0.6 on 2024-07-15 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
        ('course', '0002_remove_review_user_remove_video_duration_and_more'),
        ('users', '0002_remove_profile_social_remove_profile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techtolearn',
            name='thumbnail',
            field=models.ImageField(upload_to='techImages/'),
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesubscription', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.profile')),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': True,
            },
        ),
    ]
