# Generated by Django 5.0.6 on 2024-07-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0002_alter_techtolearn_thumbnail_subscriptions'),
        ('course', '0002_remove_review_user_remove_video_duration_and_more'),
        ('users', '0013_remove_otpverify_user_otpverify_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='video',
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_id', to='course.module'),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to='users.profile'),
        ),
    ]
