# Generated by Django 5.0.6 on 2024-07-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_profile',
            field=models.CharField(default='', max_length=255),
        ),
    ]
