# Generated by Django 5.0.6 on 2024-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0002_jobposting_job_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='years_of_experience',
            field=models.TextField(),
        ),
    ]
