# Generated by Django 5.0.6 on 2024-07-15 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='users.user'),
        ),
    ]
