# Generated by Django 5.0.4 on 2024-07-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDefault',
        ),
        migrations.AlterModelTable(
            name='userdefault',
            table='userDefault',
        ),
    ]
