# Generated by Django 5.0.4 on 2024-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverify',
            name='user',
        ),
        migrations.AddField(
            model_name='otpverify',
            name='phone_number',
            field=models.CharField(default='sad', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpverify',
            name='otp',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
