# Generated by Django 5.0.4 on 2024-07-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments_posts',
        ),
    ]
