# Generated by Django 5.0.4 on 2024-07-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_comments_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': False},
        ),
    ]
