# Generated by Django 5.0.4 on 2024-07-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': True},
        ),
    ]
