# Generated by Django 5.0.4 on 2024-07-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
