# Generated by Django 5.0.4 on 2024-07-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_comments_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='message',
            new_name='change',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
    ]
