# Generated by Django 5.0.4 on 2024-07-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_comments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='chasadasdnge',
            field=models.TextField(default='sadsa'),
            preserve_default=False,
        ),
    ]
