# Generated by Django 5.0.4 on 2024-07-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_comments_chasadasdnge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
