# Generated by Django 5.0.6 on 2024-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_postcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='Post',
            new_name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
