# Generated by Django 5.0.4 on 2024-07-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_rename_post_postcomments_post_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
